version: '3.8'

services:
    database:
        container_name: petflix-database
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        restart: always
        networks:
            - net
    server:
        container_name: petflix-server
        build: .
        image: petflix-server
        restart: always
        command: npm run start:prod
        environment:
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@petflix-database:5432/petflix
        ports:
            - 3232:3000
        networks:
            - net
        depends_on:
            - database

networks:
    net:
        driver: bridge
