export * from './UserRoute';
export * from './ReactRoute';
export * from './EvaluationRoute';
export * from './RankingRoute';
export * from './MovieRoute';
export * from './MoviesApiRoute';
export * from './AdminRoute';
export * from './AvatarRoute';
export * from './QuoteRoute';
